class GovernanceBountyEngine:
    @staticmethod
    calculate_whitehat_bounty(base_bounty, seized_collateral_usd, bonus_percentage=0.005):
        """Calculates white-hat bounty including a percentage increase from seized attacker funds."""
        bonus = seized_collateral_usd * bonus_percentage
        total_payout = base_bounty + bonus
        return {
            "base_bounty": base_bounty,
            "seized_pool": seized_collateral_usd,
            "percentage_increase": f"{bonus_percentage * 100}%",
            "bonus_awarded": bonus,
            "total_payout": total_payout
        }

    @staticmethod
    def simulate_hardware_cooption(attacker_hash_ghz, duration_hours=24):
        """Calculates DePIN yield generated by re-routing confiscated hardware."""
        efficiency_eta = 0.85
        yield_generated = attacker_hash_ghz * efficiency_eta * duration_hours
        return {
            "attacker_compute": f"{attacker_hash_ghz} GHz",
            "coopted_duration": f"{duration_hours} Hours",
            "depin_bandwidth_units": round(yield_generated, 2),
            "allocation": "80% Treasury POL / 20% L1 Miner Pool"
        }
